apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}"
  namespace: "{{ .Values.nameSpace }}"
  labels:
    app: "{{ .Chart.Name }}"
    chart: "{{ .Chart.Name }}"
    version: "{{ .Chart.Version }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
    name: {{ .Values.service.name }}
  selector:
    app: "{{ .Chart.Name }}"
    chart: "{{ .Chart.Name }}"
    version: "{{ .Chart.Version }}"