# GitHub Actions docs
# https://help.github.com/en/articles/about-github-actions
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: marketplace

on: [push]

jobs:
  build:

    # Machine environment:
    # https://help.github.com/en/articles/software-in-virtual-environments-for-github-actions#ubuntu-1804-lts
    # We specify the Node.js version manually below, and use versioned Chrome from Puppeteer.
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.8
      uses: actions/setup-node@v1
      with:
        node-version: 12.8
    - uses: intelligo-systems/intelligo-actions@v1  
      with:
        packages: '["intelligo", "intelligo-cli", "neuro.js", "uptime.js", "@devmn/stepper", "@devmn/image-viewer", "@devmn/multi-select"]'  
    - name: Install dependencies
      run: npm install
      working-directory: ./marketplace
    - name: Build
      run: npm run build
      working-directory: ./marketplace
      env:
        CI: true
